name: Deploy Infrastructure
on:
  push:
    branches:
      - main
jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build and Deploy Infrastructure
        run: |
          sam build
          sam deploy --stack-name poc-dynamodb-table --resolve-s3 --capabilities CAPABILITY_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
